# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Hexo
subtitle:
description:
keywords:
author: Xcmy
language:
timezone:


# Here is some simple markdown.



# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://39.105.67.172/blog/
root: /blog/
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page



# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: minos

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:



### 后加
menu:
  Archives: /archives
#  Lifestyle: /lifeStyle
#  Music: /music
  Technology: /technology
  About: /about

search:
  type: insight

share:
  type: sharethis
  install_url: http://39.105.67.172/blog/

comment:
  type: disqus
  shortname: xcmy

plugins:
  mathjax: true
  gallery: true
  google-analytics:
    tracking_id:

navbar_links:
  GitHub:
    icon: fab fa-github
    url: https://github.com/xcmy

footer_links:
  GitHub: https://github.com/xcmy
